<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <Authors>Remoter contributors</Authors>
    <Version>0.1.0</Version>
  </PropertyGroup>
</Project>
